services:
  - type: web
    name: BLADE-MD
    runtime: node
    region: frankfurt
    plan: free
    repo: https://github.com/Loukson/BLADE-MD.git
    branch: main
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: Dockerfile
    autoDeploy: true
